apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: study
rules:
  - apiGroups: [""]
    resources: [pods]
    verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: orders-read-pods
  namespace: study
subjects:
  - kind: ServiceAccount
    name: orders
    namespace: study
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader
